export const API = {
  ACCOUNT_LOGIN: '/account/login',
  ACCOUNT_REGISTER: '/account/register',
  ACCOUNT_PROFILE: '/account/profile',
  ACCOUNT_CONFIRM: '/account/confirm',
  ACCOUNT_FORGOT: '/account/password/forget',
  ACCOUNT_RECOVER: '/account/password/recover',
  ACCOUNT_PROFILE_UPDATE: '/account/profile/update',
  ACCOUNT_PASSWORD_CHANGE: '/account/password/change',
  ACCOUNT_EMAIL_CHANGE: '/account/email/change',
  ACCOUNT_PHONE_CHANGE: '/account/phone/change',
  ACCOUNT_PHONE_CONFIRM: '/account/phone/change/confirm',
  ACCOUNT_EMAIL_CONFIRM: '/account/email/change/confirm',
  ACCOUNT_RESEND_VERIFICATION: (id: string) => `/account/resend/verification/${id}`,
  ACCOUNT_DEVICES: '/account/devices',
  ACCOUNT_DEVICES_ADD: '/account/devices/add',
  ACCOUNT_DEVICES_REMOVE: (id: string) => `/account/devices/remove/${id}`,
  ACCOUNT_DEVICES_TOGGLE: (id: string) => `/account/devices/toggle/${id}`,
  ACCOUNT_DEVICES_RENAME: (id: string) => `/account/devices/rename/${id}`,
  ACCOUNT_MEMBER_PROFILE: (userId: string) => `/account/profile/${userId}`,
  GROUPS_LIST: '/groups/list',
  GROUPS_ARCHIVED: '/groups/archived',
  GROUPS_CREATE: '/groups/create',
  GROUPS_EDIT: (id: string) => `/groups/${id}/edit`,
  GROUPS_REMOVE: (id: string) => `/groups/${id}/remove`,
  GROUPS_ARCHIVE: (id: string) => `/groups/${id}/archive`,
  GROUPS_RESTORE: (id: string) => `/groups/${id}/restore`,
  GROUPS_FETCH: (id: string) => `/groups/${id}/fetch`,
  GROUPS_ADD_ACCESS: (id: string) => `/groups/${id}/add-access`,
  GROUPS_CHANGE_ACCESS: (id: string) => `/groups/change-access/${id}`,
  GROUPS_REMOVE_ACCESS: (id: string) => `/groups/remove-access/${id}`,
  GROUPS_CHANGE_PENDING: (id: string) => `/groups/change-pending-access/${id}`,
  GROUPS_REMOVE_PENDING: (id: string) => `/groups/remove-pending-access/${id}`,
  GROUPS_TOGGLE_ENTRY: (id: string) => `/groups/toggle-entry/${id}`,
  GROUPS_REMOVE_ENTRY: (id: string) => `/groups/remove-entry/${id}`,
  GROUPS_EDIT_ENTRY: (id: string) => `/groups/edit-entry/${id}`,
  GROUPS_MANUAL_ENTRY: (id: string) => `/groups/manual-entry/${id}`,
  GROUPS_CREATE_SHIFT: (id: string) => `/groups/shifts/${id}/create`,
  GROUPS_EDIT_SHIFT: (id: string) => `/groups/shifts/${id}/edit`,
  GROUPS_REMOVE_SHIFT: (id: string) => `/groups/shifts/${id}/remove`,
  GROUPS_TIME_OFF_REQUEST: (id: string) => `/groups/time-offs/${id}/request`,
  GROUPS_TIME_OFF_DELETE: (id: string) => `/groups/time-offs/${id}/delete`,
  GROUPS_TIME_OFF_APPROVE: (id: string) => `/groups/time-offs/${id}/approve`,
  GROUPS_TIME_OFF_DECLINE: (id: string) => `/groups/time-offs/${id}/decline`,
  GROUPS_TIME_OFF_DETAIL: (id: string) => `/groups/time-offs/${id}/detail`,
  GROUPS_TIMESPENT: (id: string) => `/times/group/${id}`,
  GROUPS_REPORT: (id: string) => `/groups/${id}/report`,
  GROUPS_UPGRADE: (id: string) => `/groups/${id}/upgrade`,
  GROUPS_NOT_ATTACHED: (id: string) => `/groups/${id}/non-attached`,
  GROUPS_CONNECT: (parentId: string) => `/groups/${parentId}/connect`,
  PROJECTS_LIST: '/projects/list',
  PROJECTS_ARCHIVED: '/projects/archived',
  PROJECTS_FETCH: (id: string) => `/projects/${id}/fetch`,
  PROJECTS_CREATE: '/projects/create',
  PROJECTS_EDIT: (id: string) => `/projects/${id}/edit`,
  PROJECTS_REMOVE: (id: string) => `/projects/${id}/remove`,
  PROJECTS_ARCHIVE: (id: string) => `/projects/${id}/archive`,
  PROJECTS_SUB_CREATE: (id: string) => `/projects/${id}/sub/create`,
  PROJECTS_SUB_EDIT: (id: string) => `/projects/sub/${id}/edit`,
  PROJECTS_SUB_REMOVE: (id: string) => `/projects/sub/${id}/remove`,
  PROJECTS_SUB_ORDER: (id: string) => `/projects/sub/${id}/order`,
  PROJECTS_SEASON_CREATE: (id: string) => `/projects/${id}/season/create`,
  PROJECTS_SEASON_EDIT: (id: string) => `/projects/season/${id}/edit`,
  PROJECTS_SEASON_REMOVE: (id: string) => `/projects/season/${id}/remove`,
  PROJECTS_ADD_ACCESS: (id: string) => `/projects/${id}/add-access`,
  PROJECTS_CHANGE_ACCESS: (id: string) => `/projects/change-access/${id}`,
  PROJECTS_REMOVE_ACCESS: (id: string) => `/projects/remove-access/${id}`,
  PROJECTS_CHANGE_PENDING: (id: string) => `/projects/change-pending-access/${id}`,
  PROJECTS_REMOVE_PENDING: (id: string) => `/projects/remove-pending-access/${id}`,
  PROJECTS_OBJECTIVES: (id: string) => `/projects/objectives/${id}`,
  PROJECTS_OBJECTIVE_DETAIL: (id: string) => `/projects/objectives/${id}/detail`,
  PROJECTS_TREE: (id: string) => `/projects/tree/${id}`,
  PROJECTS_ROAD_MAP: (id: string) => `/projects/road-map/${id}`,
  PROJECTS_PROGRESS: (id: string) => `/projects/progress/${id}`,
  WP_CREATE: (projectId: string) => `/work-packages/create/${projectId}`,
  WP_FETCH: (id: string) => `/work-packages/fetch/${id}`,
  WP_FETCH_ARCHIVED: (id: string) => `/work-packages/fetch/${id}/archived`,
  WP_EDIT: (id: string) => `/work-packages/${id}/edit`,
  WP_REMOVE: (id: string) => `/work-packages/${id}/remove`,
  WP_ARCHIVE: (id: string) => `/work-packages/${id}/archive`,
  WP_MERGE: (id: string, packageId: string) => `/work-packages/${id}/merge/${packageId}`,
  WP_LIST_CREATE: (id: string) => `/work-packages/${id}/lists/create`,
  WP_LIST_RENAME: (id: string) => `/work-packages/lists/${id}/rename`,
  WP_LIST_EDIT: (id: string) => `/work-packages/lists/${id}/edit`,
  WP_LIST_REPOSITION: (id: string) => `/work-packages/lists/${id}/reposition`,
  WP_LIST_CLONE: (id: string) => `/work-packages/lists/${id}/clone`,
  WP_LIST_ARCHIVE: (id: string) => `/work-packages/lists/${id}/archive`,
  WP_LIST_ARCHIVE_TASKS: (id: string) => `/work-packages/lists/${id}/archive-tasks`,
  WP_LIST_CLEAR_TASKS: (id: string) => `/work-packages/lists/${id}/clear-tasks`,
  WP_LABEL_CREATE: (id: string) => `/work-packages/labels/${id}/create`,
  WP_LABEL_RENAME: (id: string) => `/work-packages/labels/${id}/rename`,
  WP_LABEL_REMOVE: (id: string) => `/work-packages/labels/${id}/remove`,
  WP_OBJECTIVE_CREATE: (id: string) => `/work-packages/${id}/objectives/create`,
  WP_OBJECTIVE_EDIT: (id: string) => `/work-packages/objectives/${id}/edit`,
  WP_OBJECTIVE_DELETE: (id: string) => `/work-packages/objectives/${id}/delete`,
  WP_ADD_ACCESS: (id: string) => `/work-packages/${id}/add-access`,
  WP_CHANGE_ACCESS: (id: string) => `/work-packages/change-access/${id}`,
  WP_REMOVE_ACCESS: (id: string) => `/work-packages/remove-access/${id}`,
  WP_CHANGE_PENDING: (id: string) => `/work-packages/change-pending-access/${id}`,
  WP_REMOVE_PENDING: (id: string) => `/work-packages/remove-pending-access/${id}`,
  WP_SETTING: (id: string) => `/work-packages/${id}/setting`,
  WP_USER_SETTING: (id: string) => `/work-packages/${id}/setting/user`,
  WP_ORDER: (id: string) => `/work-packages/${id}/order`,
  WP_SORT_ORDERS: (id: string) => `/work-packages/${id}/sort-orders`,
  WP_PERMISSIONS: (id: string) => `/work-packages/${id}/permissions`,
  WP_LEAVE: (id: string) => `/work-packages/${id}/leave`,
  WP_UPGRADE: (id: string) => `/work-packages/${id}/upgrade`,
  WP_CONNECT: (id: string, projectId: string) => `/work-packages/${id}/connect/${projectId}`,
  WP_CUSTOM_FIELD_CREATE: (id: string) => `/work-packages/${id}/custom-fields/create`,
  WP_CUSTOM_FIELD_EDIT: (id: string) => `/work-packages/custom-fields/${id}/edit`,
  WP_CUSTOM_FIELD_REMOVE: (id: string) => `/work-packages/custom-fields/${id}/remove`,
  WP_CUSTOM_FIELD_REORDER: (id: string) => `/work-packages/${id}/custom-fields/reorder`,
  TASKS_CREATE: (listId: string) => `/tasks/${listId}/create`,
  TASKS_DETAIL: (id: string) => `/tasks/${id}/detail`,
  TASKS_CONVERT_TO_TASK: (id: string) => `/tasks/${id}/convert-to-task`,
  TASKS_CHANGE_TITLE: (id: string) => `/tasks/${id}/change-title`,
  TASKS_CHANGE_DESC: (id: string) => `/tasks/${id}/change-description`,
  TASKS_CHANGE_STATE: (id: string) => `/tasks/${id}/change-state`,
  TASKS_REPOSITION: (id: string) => `/tasks/${id}/reposition`,
  TASKS_MOVE: (id: string) => `/tasks/${id}/move`,
  TASKS_SET_DATE: (id: string) => `/tasks/${id}/set-date`,
  TASKS_LOCATION: (id: string) => `/tasks/${id}/location`,
  TASKS_MEMBER_ADD: (id: string) => `/tasks/${id}/member/add`,
  TASKS_MEMBER_REMOVE: (taskId: string, id: string) => `/tasks/${taskId}/member/${id}/remove`,
  TASKS_LABEL_ADD: (taskId: string, labelId: string) => `/tasks/${taskId}/label/add/${labelId}`,
  TASKS_LABEL_REMOVE: (taskId: string, labelId: string) => `/tasks/${taskId}/label/${labelId}/remove`,
  TASKS_ATTACHMENT_RENAME: (id: string) => `/tasks/attachment/${id}/rename`,
  TASKS_ATTACHMENT_REMOVE: (id: string) => `/tasks/attachment/${id}/remove`,
  TASKS_ATTACHMENT_COVER: (id: string) => `/tasks/attachment/${id}/cover`,
  TASKS_ATTACH: (taskId: string) => `/tasks/${taskId}/attach`,
  TASKS_COMMENT: (id: string) => `/tasks/${id}/comment`,
  TASKS_VOTE: (id: string) => `/tasks/${id}/vote`,
  TASKS_WATCH: (id: string) => `/tasks/${id}/watch`,
  TASKS_ESTIMATED: (id: string) => `/tasks/${id}/estimated`,
  TASKS_SPEND_TIME: (id: string) => `/tasks/${id}/spend-time`,
  TASKS_TOGGLE_TIMER: (id: string) => `/tasks/${id}/toggle-timer`,
  TASKS_LOGS: (id: string) => `/tasks/${id}/logs`,
  TASKS_ARCHIVE: (id: string) => `/tasks/${id}/archive`,
  TASKS_CUSTOM_FIELD_VALUE: (taskId: string, fieldId: string) => `/tasks/${taskId}/custom-field/${fieldId}/value`,
  TASKS_CALENDAR: '/tasks/calendar',
  TASKS_KARTABL: '/tasks/kartabl',
  TIMES_MINE: '/times/mine',
  MESSENGER_CHANNELS: '/messenger/channels',
  MESSENGER_FETCH: (recordId: string) => `/messenger/channel/${recordId}/fetch`,
  MESSENGER_SEND: (recordId: string) => `/messenger/channel/${recordId}/send`,
  MESSENGER_ATTACH: (recordId: string) => `/messenger/channel/${recordId}/attach`,
  MESSENGER_CHANNEL_FILES: (recordId: string) => `/messenger/channel/${recordId}/files`,
  FILES_MINE: '/files/mine',
  FILES_SHARED_BY_ME: '/files/shared-by-me',
  FILES_SHARED_BY_OTHERS: '/files/shared-by-others',
  FILES_NEW_FOLDER: '/files/new-folder',
  FILES_RENAME: '/files/rename',
  FILES_DELETE: '/files/delete',
  FILES_UPLOAD: '/files/upload',
  STORAGE_DOWNLOAD: '/storage/download',
  REPORT_DASHBOARD: '/reports/dashboard',
  REPORT_RECENT_ACTIVITIES: '/reports/recent-activities',
  SEARCH: '/search',
  CAPTCHA: '/captcha',
  CAPTCHA_CHALLENGE: '/account/captcha/challenge',
  ENUMS: '/enums',
  WORKFLOWS_LIST: '/workflows/list',
  WORKFLOWS_CREATE: '/workflows/create',
  WORKFLOWS_FETCH: (id: string) => `/workflows/${id}/fetch`,
  WORKFLOWS_EDIT: (id: string) => `/workflows/${id}/edit`,
  WORKFLOWS_REMOVE: (id: string) => `/workflows/${id}/remove`,
  WORKFLOWS_TOGGLE: (id: string) => `/workflows/${id}/toggle`,
  WORKFLOWS_EXECUTE: (id: string) => `/workflows/${id}/execute`,
  WORKFLOWS_EXECUTIONS: (id: string) => `/workflows/${id}/executions`,
} as const;
